- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/SentryApple.kt
This allows the user to capture exceptions and errors directly in swift code and it also serves as a convenience method for the iosMain part of the KMP app. Additionally, the NSException creation has been changed to use the throwable name which is more descriptive.
> feat: Add iOS specific extension methods

- sentry-kotlin-multiplatform/build.gradle.kts
- sentry-kotlin-multiplatform/sentry_kotlin_multiplatform.podspec
- sentry-samples/kmp-app/iosApp/Podfile.lock
- sentry-samples/kmp-app/shared/build.gradle.kts
- sentry-samples/kmp-app/shared/shared.podspec
This version introduces fixes to false positives of OutOfMemory errors in simulators:
Fixes: #15 
Related: https://github.com/getsentry/sentry-cocoa/pull/1970
> chore: Bump Sentry Cocoa SDK version to 7.21.0

- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/UserExtensions.kt
In `commonAppleMain` UserExtensions there was a missed `toString` call that was breaking compilation
> Fix compilation error caused by not calling `toString` 

- README.md
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Config.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- sentry-kotlin-multiplatform/build.gradle.kts
- sentry-kotlin-multiplatform/sentry_kotlin_multiplatform.podspec
- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/Attachment.kt
- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.kt
- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/protocol/SentryId.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/Attachment.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/protocol/SentryId.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/protocol/Breadcrumb.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/protocol/User.kt
- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/AttachmentTest.kt
- sentry-samples/kmp-app/androidApp/build.gradle.kts
- sentry-samples/kmp-app/androidApp/src/main/java/sample/kmp/app/android/MainActivity.kt
- sentry-samples/kmp-app/build.gradle.kts
- sentry-samples/kmp-app/desktopApp/src/jvmMain/kotlin/sample.kmp.app.desktop/Main.kt
- sentry-samples/kmp-app/iosApp/Podfile.lock
- sentry-samples/kmp-app/shared/build.gradle.kts
- sentry-samples/kmp-app/shared/shared.podspec
- sentry-samples/kmp-app/shared/src/commonMain/kotlin/sample.kmp.app/AppSetup.kt
- settings.gradle.kts
this PR should fix most issues regarding the build and bump versions of Kotlin and Multiplatform especially #44
additionally, I confirmed the correctness of the artifacts by publishing them on [mymavenrepo](https://mymavenrepo.com/) and testing the SDK in sample apps. Here is the published repo: https://mymavenrepo.com/repo/IxbzFmjbPjBH4llKSvgl/
testing can be done through 
- adding the repository: `maven {
url = uri("https://mymavenrepo.com/repo/IxbzFmjbPjBH4llKSvgl/")
}`
- importing the dependency in gradle for example: `api("io.sentry:sentry-kotlin-multiplatform:0.0.1")`
> fix: build and bump versions

- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.kt
for some reason the beforeBreadcrumb calls inside the option extensions got removed somewhere during a merge in the past
> fix: beforeBreadcrumb hook

- buildSrc/src/main/java/Publication.kt
Small change to rename `kotlin-tooling-metadata.json` to match the required name needed for the release
Expected: `sentry-kotlin-multiplatform-0.0.1-kotlin-tooling-metadata.json`
Example of other libraries:
- https://repo1.maven.org/maven2/co/touchlab/kermit/1.2.2/kermit-1.2.2-kotlin-tooling-metadata.json
**Testing**:
Successfully renamed:
> fix: rename kotlin tooling metadata

- .craft.yml
Adds the kmp configuration needed for a craft release:
- rootDistDir regex: matches if it's a root directory, meaning it has no "platform" identifiers.
- appleDistDir regex: matches directories of apple platforms since those contain .klib files that need to be handled differently by craft
minVersion: [1.2.0](https://github.com/getsentry/craft/releases/tag/1.2.0)
> feat(craft): kmp configuration to .craft.yml

- .craft.yml
Since we only keep track of the "main" package which is `maven:io.sentry:sentry-kotlin-multiplatform`, registering the others in the registry is not needed. We only need to upload them to maven and gh which is already done.
Ref: [#106](https://github.com/getsentry/sentry-release-registry/pull/106)
> chore: remove other sdks in .craft.yml

- README.md
The current init code is not entirely correct and leads to compile errors.
> chore(readme): update init code

- CHANGELOG.md
- sentry-kotlin-multiplatform/build.gradle.kts
Fixes #60 
Reason is that on API 23 and below `SentryAndroid` depends on some `Sentry` functions internally so that's why we cannot exclude it.
> fix: Android init crash on API level 23 and below

- CHANGELOG.md
- README.md
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryKMP.kt
- sentry-samples/kmp-app/iosApp/iosApp/iOSApp.swift
Add `@HiddenFromObjc` annotation to hide `init` with context from Cocoa targets.
This is very useful if we want to have certain things hidden to make the Swift experience better in general
https://kotlinlang.org/docs/native-objc-interop.html
> feat: improve Objc/Swift experience with HiddenFromObjc

- CHANGELOG.md
- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/HttpStatusCodeRange.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryOptions.kt
- sentry-samples/kmp-app/iosApp/iosApp/ContentView.swift
- sentry-samples/kmp-app/iosApp/iosApp/iOSApp.swift
- sentry-samples/kmp-app/shared/src/commonMain/kotlin/sample.kmp.app/AppSetup.kt
- sentry-samples/kmp-app/shared/src/iosMain/kotlin/sample.kmp.app/HttpClient.kt
It is currently not possible to configure http client errors captured on Apple targets: #75
> feat: configuring http client errors for Apple targets

- CHANGELOG.md
- Makefile
- build.gradle.kts
- buildSrc/src/main/java/Config.kt
- hooks/pre-commit
- sentry-kotlin-multiplatform/api/android/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/api/jvm/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/build.gradle.kts
ensures that our API won't introduce breaking changes unnoticed.
Unfortunately native targets are not supported yet but it's a good start to have checks at least for JVM and Android
> chore: add api checks with binary compatibility plugin

- CHANGELOG.md
- sentry-kotlin-multiplatform/src/androidMain/AndroidManifest.xml
- sentry-samples/kmp-app-cocoapods/androidApp/src/main/AndroidManifest.xml
- sentry-samples/kmp-app-mvvm-di/androidApp/src/main/AndroidManifest.xml
- sentry-samples/kmp-app-spm/androidApp/src/main/AndroidManifest.xml
Introduces #89 so the user doesn't have to manually disable the init through AndroidManifest.
> Automatically disable `io.sentry.auto-init`

- README.md
Ref: #90 
Removes init and configuration doc and instead refers to the sentry-doc documentation in `Resources`
> chore: update docs 

- README.md
README: Adds a badge to the dokka/kotlin doc github page.
> chore: Add kdoc/dokka reference in README

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-kotlin-multiplatform/build.gradle.kts
- sentry-kotlin-multiplatform/src/androidMain/AndroidManifest.xml
- sentry-kotlin-multiplatform/src/androidMain/kotlin/io/sentry/kotlin/multiplatform/SentryInit.android.kt
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/BaseSentryTest.kt
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/ContextProviderTest.kt
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/SentryContextProviderTest.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/SentryBridge.jvm.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryKMP.kt
- sentry-kotlin-multiplatform/src/jvmMain/kotlin/io/sentry/kotlin/multiplatform/SentryInit.jvm.kt
- sentry-samples/kmp-app-cocoapods/androidApp/src/main/java/sample/kmp/app/android/MainActivity.kt
- sentry-samples/kmp-app-cocoapods/shared/src/commonMain/kotlin/sample.kmp.app/SentrySetup.kt
- sentry-samples/kmp-app-mvvm-di/androidApp/src/main/kotlin/sentry/kmp/demo/android/MainApp.kt
- sentry-samples/kmp-app-mvvm-di/iosApp/AppDelegate.swift
- sentry-samples/kmp-app-mvvm-di/shared/src/commonMain/kotlin/sentry.kmp.demo/sentry/SentrySetup.kt
- sentry-samples/kmp-app-spm/androidApp/src/main/java/sample/kmp/app/android/MainActivity.kt
- sentry-samples/kmp-app-spm/shared/src/commonMain/kotlin/sample.kmp.app/SentrySetup.kt
Ref #114 
Eliminates the need for context in init - context can be passed in through a simple `ContextProvider`.
> Remove need for context in Sentry.init for Android 

- scripts/update-cocoa.sh
Fixes fetching and setting of the version which causes it to fail for cocoa: https://github.com/getsentry/sentry-kotlin-multiplatform/actions/runs/6665350889/job/18114812485
Locally ran the script and verified the version
> Fix get version for cocoa in sentry deps bot

- CHANGELOG.md
- config/detekt/detekt.yml
- sentry-kotlin-multiplatform/api/android/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/api/jvm/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/src/commonAppleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.apple.kt
- sentry-kotlin-multiplatform/src/commonAppleTest/kotlin/io/sentry/kotlin/multiplatform/FoundationTest.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.jvm.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryOptions.kt
- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/SentryOptionsTest.kt
> Add sample rate configuration

- buildSrc/src/main/java/Publication.kt
Fixes the publish on craft which expects a `*-all.jar` file but this is not created anymore in the current Kotlin version.
So this creates a placeholder jar file until we can fix the craft implementation directly.
> chore: fix publish by adding -all.jar file

- buildSrc/src/main/java/Publication.kt
fixes the cinterop part of the publish
cinterop klib files are now generated in another build folder in the current Kotlin version that's why they weren't included in the dist
> chore: fix cinterop problem for publish

- .github/workflows/update-deps.yml
> fix: updater config v2

- CHANGELOG.md
- sentry-kotlin-multiplatform/api/android/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/api/jvm/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/SentryBridge.apple.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/SentryBridge.jvm.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryBridge.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryKMP.kt
Adds `isCrashedLastRun`
**Note**: codecov ci fails because I haven't added any test, not sure what the best way to test here is since mocking on KMP is not really a thing yet
Closes https://github.com/getsentry/sentry-kotlin-multiplatform/issues/178
Manually
> Add isCrashedLastRun

- CHANGELOG.md
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/nsexception/SentryUnhandledExceptions.kt
Makes the `setSentryUnhandledExceptionHook` api public so users can initialize the iOS SDK themselves and drop the unhandled exceptions created automatically that doesn't have useful information. See [here](https://github.com/rickclephas/NSExceptionKt?tab=readme-ov-file#why-this-library)
Closes #200 
X
> Make `setSentryUnhandledExceptionHook` public

- README.md
> Update README.md for Apple Privacy Manifest

- CHANGELOG.md
- sentry-kotlin-multiplatform/src/androidMain/kotlin/io/sentry/kotlin/multiplatform/SentryInit.android.kt
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/SentryContextProviderTest.kt
`lateinit` crashes the application if not set for example when using the Phoenix library
When calling `ProcessPhoenix.triggerRebirth(context)` the app is actually restarted twice and only one the second time the content providers are loaded.
Fixes #212 
Manual, `SentryContextProviderTest`
> Fix: don't crash app when `applicationContext` is not available

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
There is a known issue with compiling on xcode `15.3` that is fixed only on Kotlin `1.9.23` and higher.
We are on `1.9.21` and I have to change it to `1.9.23` every time when developing on KMP.
See: https://youtrack.jetbrains.com/issue/KT-65542/Cinterop-tasks-fails-if-Xcode-15.3-is-used
I'm not sure about the backwards compatibility implications but I think it's fine?
@romtsn
> Update Kotlin version to `1.9.23`

- .github/workflows/update-deps.yml
- scripts/update-cocoa.sh
- sentry-kotlin-multiplatform-gradle-plugin/gradle.properties
Cocoa version should also update for the plugin
> feat(gh-action): update gradle plugin cocoa version

- CHANGELOG.md
- sentry-kotlin-multiplatform-gradle-plugin/build.gradle.kts
- sentry-kotlin-multiplatform-gradle-plugin/src/main/java/io/sentry/kotlin/multiplatform/gradle/SourceSetAutoInstallExtension.kt
- sentry-kotlin-multiplatform-gradle-plugin/src/test/java/io/sentry/kotlin/multiplatform/gradle/SentryPluginTest.kt
Don't always use latest version.
Keeps versioning predictable
Unit test
> feat(plugin): dont use `latest.release` as default for the KMP dependency

- buildSrc/src/main/java/Publication.kt
Current way of fetching the javadoc only works on 1 digit e.g `0.9.0` but not 2 digits `0.10.0`
> fix(publish): fetch javadoc for 2 digit release numbers

- CHANGELOG.md
- sentry-kotlin-multiplatform/api/android/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/api/jvm/sentry-kotlin-multiplatform.api
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/PlatformOptions.android.kt
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.apple.kt
- sentry-kotlin-multiplatform/src/appleTest/kotlin/io/sentry/kotlin/multiplatform/PlatformOptions.apple.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io/sentry/kotlin/multiplatform/extensions/SentryOptionsExtensions.jvm.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryOptions.kt
- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/PlatformOptions.kt
- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/SentryOptionsTest.kt
- sentry-kotlin-multiplatform/src/jvmTest/kotlin/io/sentry/kotlin/multiplatform/PlatformOptions.jvm.kt
Add diagnostic level option
Closes #286 
Unit test
> feat: add diagnostics level

- README.md
> Update README.md with cocoa version compat

- CHANGELOG.md
- sentry-kotlin-multiplatform-gradle-plugin/src/main/java/io/sentry/kotlin/multiplatform/gradle/DerivedDataPathValueSource.kt
> fix(plugin): check exit value when executing `xcodebuild` command 

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/workflows/generate-dokka.yml
- .github/workflows/kotlin-multiplatform-gradle-plugin.yml
- .github/workflows/kotlin-multiplatform.yml
> chore: Adds default issue types to issue templates

- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-kotlin-multiplatform/build.gradle.kts
- sentry-kotlin-multiplatform/src/androidMain/kotlin/io/sentry/kotlin/multiplatform/SentryPlatformOptions.android.kt
- sentry-kotlin-multiplatform/src/androidUnitTest/kotlin/io/sentry/kotlin/multiplatform/SentryAndroidBridgeTest.kt
Closes https://github.com/getsentry/sentry-kotlin-multiplatform/issues/313
> misc(android): update native android sdk name

- README.md
> Update sentry cocoa version compat in README.md

- .craft.yml
Blocked by https://github.com/getsentry/craft/pull/612 and it must be released first
> chore: update craft config to support publish of new targets

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/maintainer-blank.yml
replaces usage of GH issue type and platform label to Linear-compatible labels
GH issue types will be deprecated internally by August 14
> chore(GH): Update GH issue templates for Linear compatibility
