- .craft.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Publication.kt
- gradle.properties
- scripts/bump-version.sh
- scripts/mvnw
- scripts/mvnw.cmd
- scripts/settings.xml
- sentry-kotlin-multiplatform/build.gradle.kts
Added the necessary config and scripts to run a Sentry release.
> feat: Add release process

- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/SentryApple.kt
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/TypeAliases.kt
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/extensions/UserFeedbackExtensions.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io.sentry.kotlin.multiplatform/SentryJvm.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io.sentry.kotlin.multiplatform/TypeAliases.kt
- sentry-kotlin-multiplatform/src/commonJvmMain/kotlin/io.sentry.kotlin.multiplatform/extensions/UserFeedbackExtensions.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryBridge.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/SentryKMP.kt
- sentry-kotlin-multiplatform/src/commonMain/kotlin/io/sentry/kotlin/multiplatform/protocol/UserFeedback.kt
- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/UserFeedbackTest.kt
- sentry-samples/kmp-app/desktopApp/build.gradle.kts
- sentry-samples/kmp-app/shared/src/commonMain/kotlin/sample/kpm_app/LoginImpl.kt
This PR allows the KMP SDK to capture UserFeedback. The implementation is simple: wrapping data around and transforming it to the platform specific UserFeedback when forwarding it
> feat: user feedback

- buildSrc/src/main/java/Publication.kt
- sentry-kotlin-multiplatform/build.gradle.kts
Renamed files to match the module name, removed debug aar, fixed javadoc jars and included necessary klibs for apple targets
> fix: publish file generation

- .craft.yml
Craft 1.2.1 will include the fix.
Can be merged as soon as 1.2.1 is released
> use craft 1.2.1

- .github/workflows/danger.yml
> chore: add danger

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/maintainer-blank.yml
- .github/pull_request_template.md
Related: https://github.com/getsentry/sentry-kotlin-multiplatform/issues/96
Add issue and pr templates for this repo.
> chore: issue & pr templates

- README.md
> readme: drop experimental

- .run/iosApp-spm.run.xml
- CHANGELOG.md
- buildSrc/src/main/java/Config.kt
- sentry-kotlin-multiplatform/sentry_kotlin_multiplatform.podspec
- sentry-kotlin-multiplatform/src/appleMain/kotlin/io/sentry/kotlin/multiplatform/nsexception/SentryUnhandledExceptions.kt
- sentry-kotlin-multiplatform/src/nativeInterop/cinterop/SentryNSException/Private/SentryCrashMonitor_NSException+NSExceptionKt.h
- sentry-samples/kmp-app-cocoapods/iosApp/Podfile.lock
- sentry-samples/kmp-app-cocoapods/shared/build.gradle.kts
- sentry-samples/kmp-app-cocoapods/shared/shared.podspec
- sentry-samples/kmp-app-spm/iosApp.xcodeproj/project.pbxproj
- sentry-samples/kmp-app-spm/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Update to Cocoa v8.17.1

- .github/workflows/update-deps.yml
> deps: bump sentry deps updater to v2

- .github/workflows/kotlin-multiplatform.yml
- CHANGELOG.md
> Add back CHANGELOG entry from 0.3.0 and update .github required workflow

- buildSrc/src/main/java/Publication.kt
should now be fixed for sure (🤞 )
verified correctness by checking the generated distribution folder of the workflow
> chore: fix publish

- .github/workflows/kotlin-multiplatform.yml
> ci: change macos runners

- .github/workflows/kotlin-multiplatform.yml
> ci: fix codecov

- CHANGELOG.md
- sentry-kotlin-multiplatform/build.gradle.kts
Fixes https://github.com/getsentry/sentry-kotlin-multiplatform/issues/224
> fix symbol multiply defined

- .github/workflows/kotlin-multiplatform.yml
Committed via https://github.com/asottile/all-repos
> all-repos: update actions/upload-artifact to v4

- README.md
> Update Kotlin `1.9.21` to `1.9.23` in README.md

- README.md
> Add Cocoa compatibility for KMP `0.11.0` in README

- .github/dependabot.yml
> Add dependapot

- sentry-kotlin-multiplatform/src/commonTest/kotlin/io/sentry/kotlin/multiplatform/SentryE2ETest.kt
There has been some flakes so let's increase the waiting time
> chore(e2e-test): increase time to wait for event to arrive in sentry

- .github/workflows/kotlin-multiplatform-gradle-plugin.yml
- .github/workflows/kotlin-multiplatform.yml
> ci: trigger workflows only for specific paths
